# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a589aa8091f776d2d151fff5daa1b62ebaf1a87de7de9e16c6ee8ac9f82293e6ebd073cdc52f0bdd7e8f631996461d84dd2e5476cb438f01e36e4d0e248fa80

test:
  secret_key_base: 4eebf18b72891d26188cc1b236307ce5a4e8efcdc682716c98148f5d1a535a3394599aca5053673206db29e34166646894b243581ca3a07ce988e388185a8e91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
